### ISSUE TITLE
command to generate password issuing error

### ISSUE THREAD

**Issue by karuturi99** [calvinsettachatgul/calnav#9]
PASSWORD= ${RANDOM} -head -c3
echo $PASSWORD
when i execute above commands using scripts i am getting an error output as blank

**Comment by calvinsettachatgul** [comment]
this worked for me on my mac
PASSWORD=$((RANDOM | head -c3))

**Comment by calvinsettachatgul** [comment]
@karuturi99 hey did you get this to work?

**Comment by karuturi99** [comment]
[vagrant@localusers vagrant]$ ./random.sh 
22015
24546
[vagrant@localusers vagrant]$ cat random.sh 
#!/bin/bash
P=${RANDOM}
echo ${P}
PASSWORD=$((RANDOM | head -c3))
echo $PASSWORD


[vagrant@localusers vagrant]$

**Comment by karuturi99** [comment]
i was expecting a 3 digit out put but i see no change with the output.

**Comment by karuturi99** [comment]
user1:~/environment/calnav/linux_bash (master) $ ./random.sh 
1687
9795
user1:~/environment/calnav/linux_bash (master) $ pwd
/home/ec2-user/environment/calnav/linux_bash
user1:~/environment/calnav/linux_bash (master) $ 

for testing i placed it in above script. was not successful. i will take a look into it 2marrow

**Comment by calvinsettachatgul** [comment]
issues are for uncovering actionable changes to the repo
closing this because no change can take place
this is just a question about having some errors no change will result in a pr
